### ISSUE TITLE
Query regarding feature extraction from DINO

### ISSUE THREAD

**Issue by rahul-goel** [dichotomies/N3F#1]
Hi!
From my usage of DINO's feature extractor, I saw that it outputs a single feature vector per image. But for 2D feature supervision we need per-pixel features. Could you elaborate how you did that?

The paper mentions about taking some patches with DINO. It is not clear to me. Are you taking 16x16 patches and associating the calculated feature vector with the pixel at the center of the patch? If this is the case, how are you padding the input image?

Additionally, could you explain why are the features calculated (in the uploaded Google Drive data) for images that have been scaled down 64 times horizontally and vertically? What is the reason for such a low resolution image?

**Comment by dichotomies** [comment]
The ViT-based architecture of DINO (implementation [here](https://github.com/facebookresearch/dino/blob/main/vision_transformer.py)) takes as input a sequence of non-overlapping image patches of resolution N × N (we used two variants, one with N=8 and N=16), which are then encoded. The patch size effectively results in a downsampling of the input image by a factor N. Regarding the output, the first output token (the [CLS] token) aggregates information from the entire sequence and is typically used as the single-vector representation of the input image. However, the remaining output tokens can be used as the "spatial" representation of the input, which is what we use here. We also plan to release the feature extraction code soon.

Regarding the resolution: as long as you make sure that you train NeRF with the same resolution as the one used for extracting the DINO features you can also use also other resolutions (to make the evaluation comparable).

**Comment by rahul-goel** [comment]
Hi again!
I've been trying to replicate the results produced by DINO on the scene "horns" to match the data you have given. But I am failing to do so.
Here is the method I am using: https://gist.github.com/rahul-goel/69950246aaf13284ac836cccccc3733c

I've also edited the `VisionTransformer` to return all the tokens but the CLS token as shown below:
```
    def forward(self, x):
        x = self.prepare_tokens(x)
        for blk in self.blocks:
            x = blk(x)
        x = self.norm(x)
        return x[:, 1:, :]
```

Could you point out to a mistake I am making? Or alternatively could you share the code you've used so that we can replicate the results.

**Comment by StefanZt** [comment]
Hello!
I am still confused on how to get a feature vector per-pixels. i can only get a single feature vector per image.
any answers will be appreciated!

**Comment by rahul-goel** [comment]
@StefanZt Hi!
The feature vector that you get per image in DINO is the CLS Token. As you can see [here](https://github.com/facebookresearch/dino/blob/main/vision_transformer.py#L214), only the CLS token is returned instead of the entire output. You can get the features by taking everything except this CLS token instead.

As for per pixel features are concerned, DINO makes features patch-wise. So you'll get features for a patch of pixels which you can associate with the multiple underlying pixels.

**Comment by StefanZt** [comment]
@rahul-goel Thanks a lot!

**Comment by dichotomies** [comment]
Hi,

I've added a script for extracting DINO features. Please follow the instructions shown [here](https://github.com/dichotomies/N3F#dino-feature-extractor-for-additional-nerf-scenes-and-custom-scenes) to get it working on your own data.

Hope this is helpful @rahul-goel @StefanZt. I'll close this issue for now, but feel free to open if you run into issues.
